//operators
food=20;
tip=0.2;
tipamount=food*tip;
console.log(tipamount);
/*
/*         first website of fruit */
//user input
/*meal=Number(prompt('what is your favourite meal'));
fruit=prompt("waht is yur favourite fruit");

//calculating the total food and total amount to be needed
foodamount=Number(prompt("how much food you want?"));
tippercentage=Number(prompt("how much tip(percentage) is given in your hotel?"))/100;
Totaltipamount=foodamount*tippercentage;
Totalamount=Totaltipamount*foodamount;

console.log("Total Tip Amount taken from customer would be the  "+Totaltipamount +"$");

console.log("Total Payment gone upto the " + Totalamount+" $");
//alert is used for the for he output
alert(Totaltipamount);
*/


//data types
/*
1.Number  1,2,3,4,5,6,7
2.string='hello' "vishwas"
3.boolean =true false
4.objects{}
5.arrays
*/

/*Maths operations
1.multiply
2.modulo
3.divison
4.addition
5.subtraction
6.exponents
*/




/*Math methods
floor =round down Math.floor(21.035)-----> 21
ceil=round up     Math.ceil(21.34)--->22
random=generate the number between the 0 and 1 Math.random()--->any number between 0 and 1
If we want to get the number between the 0 and n num ber then multiply the Math.random by *number\
//how to cut this long function into small numbers
use floor to get smallest number closer to number get generated by the Mtah.random()
example:::::Math.floor(Math.random()*3);
*/

/*
//Type of variables
let name='vishwas';//let have local scope 
console.log(name);


const vish=100;//this const value does not changed
console.log(vish);
*/

/*___________________Tiny Weather App____________________*/

//if rain then ------->>>>>>"grab your umbrella"
//else then ---------->>>>>>"wear your sunglasses"



//code for this tiny app 
let weather=prompt("Please tell me your weather condition in your area");
if(weather=='rain')
    console.log("Grab The Umbrella");
else
    console.log('Wear your sunglasses');




